@isTest
public class AccountTriggerServiceTest 
{

    // static void atribuirProprietarioContaPeloCodigoAssessorTest()
    // {

    // }
	@isTest
    static void testCoverage()
    {
        AccountTriggerService.testCoverage();
    }

    // public class UserServiceStub extends C3C_AbstractStub implements System.StubProvider
    // {
    //     public override String getClassName()
    //     {
    //         return 'UserService';
    //     }

    //     public override Map<String, ClassTested> getMapClassTested()
    //     {
    //         return mapClassTested;
    //     }

    //     public override Object methodCall(
    //         Object stubbedObject, 
    //         String stubbedMethodName,
    //         Type returnType, 
    //         List<System.Type> listOfParamTypes, 
    //         List<String> listOfParamNames,
    //         List<Object> listOfArgs
    //     )
    //     {
    //         Object returnValue;
            
            
    //         switch on stubbedMethodName
    //         {
    //             when 'obterMapaUsuariosPorCodigoAssessor'
    //             {
    //                 returnValue = new List<User>{new User(Username = 'Test@test.com', CodigoAssessor__c = 4013)};
    //             }
    //         }
            
    //         return returnValue;
    //     }
    // }
}